version: '3.8'

services:
  mysql:
    image: mysql
    container_name: crypto_exchange
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crypto_exchange
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
      - ./init-sql:/docker-entrypoint-initdb.d
    restart: always

  app:
    build: .
    container_name: crypto-c2c-api
    ports:
      - "5000:5000"
    environment:
      - HOST_DB=mysql
      - USER_DB=user
      - PASSWORD_DB=password
      - NAME_DB=crypto_exchange
      - PORT=5000
    depends_on:
      - mysql
    volumes:
      - .:/app
    command: node server.js
    restart: always
